### PR TITLE
add data on device test and example

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
also fixes caliper defines

**Review by nicolemarsaglia — APPROVED** [review]
Looks good! I like the two test cases!

**Comment by cyrush** [comment]
Screenshot 2024-08-29 at 2 57 24 PM

My baselines (created w/o OpenMP) have a different scalar range vs what is running in CI.

**Comment by cyrush** [comment]
I tried forcing serial, instead of openmp and I was not able to reproduce a difference.  I think my initial baselines may have been bad.

**Comment by cyrush** [comment]
Serial Windows:

GetGlobalRange
[-7.21645e-16..6.66134e-16]
GetGlobalRange
[-7.21644966006352e-16..6.66133814775094e-16]

Serial macOS:
GetGlobalRange
[-7.34722e-16..5.42145e-16]


GetGlobalRange
[-7.34721528284977e-16..5.42144806295629e-16]



OpenMP:

```
[ascent annotations enabled]
GetGlobalRange
[-7.31232e-16..6.52309e-16]
GetGlobalRange
[-7.31232e-16..6.52309e-16]
```

We are contouring at zero and there is some order of ops numeric difference. 

Will switch to plotting radial which will have non zero data extents

**Pull request merged**
