### PR TITLE
Add log base 10 filter

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
*Add a log base 10 filter: "log10"
*Update Docs: Add log10 example & differentiate natural log and log10 examples.

### CODE REVIEW

**Comment by cyrush** [comment]
Changes and example look great!

Can you add a unit test that tests your example in `src/tests/ascent/t_ascent_log.cpp` as well?

**Comment by cyrush** [comment]
Also, add  changelog entry?

**Comment by nicolemarsaglia** [comment]
@cyrush I updated the changelog and added unit tests, but they don't match my example since that came from lulesh. Do you want them to match?

**Review by cyrush — APPROVED** [review]
@nicolemarsaglia  thanks for adding, everything looks good. 

It's fine if the example don't match the unit tests.

**Pull request merged**
