### PR TITLE
Merge develop into bflow-stats

### PR DESCRIPTION
**Pull request by xuanhuang1**
Merging develop for vtkm related compiling error on ascent, below is one error message that pops up in crusher build.

/ccs/home/xuanhuang/package/ascent_crusher/ascent-crusher-build-scripts/ascent_repo/ascent/src/libs/vtkh/vtkm_filters/vtkmLagrangian.cpp:3:10: fatal error: 'vtkm/filter/flow/Lagrangian.h' file not found
#include <vtkm/filter/flow/Lagrangian.h>

### CODE REVIEW

**Comment by cyrush** [comment]
@xuanhuang1  bflow stats was merged into develop in November.

It looks like you have a few changes after the merge -- Can you apply those changes to a new branch so we can work to get those into develop?

I should have suggest that you start a new branch after those changes where merged, sorry for not giving that guidance.

**Comment by xuanhuang1** [comment]
I’m a bit confused. I thought the local bflow-stats branch and develop will get merged into each other  from time to time to keep things updated (and so I created the PR that way). Why is making a new branch better here?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
This is b/c we squash merges when we move work into develop via  a PR. 

After the PR is done - we need to start with a fresh branch to avoid confusion with past history.

If not,  when you create a PR from bflow-stats into develop in the future, it would try to replay changes that are already merged in. 

If you need help replaying commits after the merge into a fresh branch, I can help with that just let me know.

**Comment by xuanhuang1** [comment]
I see. Yeah I remember some uberenv script issue hanging as well from my last attempt to update to most recent bflow-stats. Maybe it’s also due to the ascent part not synched correctly. I’ll start a new branch from latest develop and rebuild things the right way.

Can you point me to the develop <- bflow-stats merge commit so I can see what changes are made after that?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
Sure thing -- here is the PR https://github.com/Alpine-DAV/ascent/pull/945 and here is the commit: https://github.com/Alpine-DAV/ascent/commit/5b3d67bf73b36129f9c1678bd7ac89389fda9151

If you have issues creating the new branch, just let me know and I can help. 

I usually create patches to easily move changes between branches.

**Comment by cyrush** [comment]
@xuanhuang1 - were you able to complete the merge?

**Comment by xuanhuang1** [comment]
Hi Cyrus,

Just to make sure I understand. Now we are talking about the new branch bflow-topo-stats right? The old bflow-stats branch is done and should be removed from the project right?

For the new branch it's based on the current develop and I removed the ASCENT_MPI check as you suggested. I still encounter the same issue, where the uberenv script fails on raja build, and the crusher manual build sends SIGABORT on

22      0x7fffec6556b2 ascent::AscentRuntime::Execute(conduit::Node const&) + 338
21      0x7fffec6453d3 ascent::AscentRuntime::AddPublishedMeshInfo() + 451
20      0x7fffec0627a8 conduit::blueprint::mpi::mesh::number_of_domains(conduit::Node const&, int) + 184
19      0x7fffec031a84 conduit::relay::mpi::all_reduce(conduit::Node const&, conduit::Node&, int, int) + 114\
0
18      0x7fffd9f82d91 PMPI_Allreduce + 2833
17      0x7fffdbc26da7 /opt/cray/pe/lib64/libmpi_cray.so.12(+0x1eabda7) [0x7fffdbc26da7]

Xuan


________________________________

**Comment by cyrush** [comment]
Hi Xuan,

Yes:
To confirm: `bflow-topo-stats` is the new branch & we can delete the old `bflow-stats` to avoid confusion?
If that is the case, let me know and I will delete `bflow-stats`

For crusher are you using:
https://github.com/Alpine-DAV/ascent/blob/develop/scripts/build_ascent/build_ascent_hip_crusher.sh

with additional steps for babel flow deps?

-Cyrus

From: xuanhuang1 ***@***.***>
Reply-To: Alpine-DAV/ascent ***@***.***>
Date: Friday, February 17, 2023 at 10:33 AM
To: Alpine-DAV/ascent ***@***.***>
Cc: "Harrison, Cyrus D." ***@***.***>, Comment ***@***.***>
Subject: Re: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hi Cyrus,

Just to make sure I understand. Now we are talking about the new branch bflow-topo-stats right? The old bflow-stats branch is done and should be removed from the project right?

For the new branch it's based on the current develop and I removed the ASCENT_MPI check as you suggested. I still encounter the same issue, where the uberenv script fails on raja build, and the crusher manual build sends SIGABORT on

22 0x7fffec6556b2 ascent::AscentRuntime::Execute(conduit::Node const&) + 338
21 0x7fffec6453d3 ascent::AscentRuntime::AddPublishedMeshInfo() + 451
20 0x7fffec0627a8 conduit::blueprint::mpi::mesh::number_of_domains(conduit::Node const&, int) + 184
19 0x7fffec031a84 conduit::relay::mpi::all_reduce(conduit::Node const&, conduit::Node&, int, int) + 114\
0
18 0x7fffd9f82d91 PMPI_Allreduce + 2833
17 0x7fffdbc26da7 /opt/cray/pe/lib64/libmpi_cray.so.12(+0x1eabda7) [0x7fffdbc26da7]

Xuan


________________________________

**Comment by xuanhuang1** [comment]
Hi Cyrus,

Yes `bflow-topo-stats` is the new branch & we can delete the old `bflow-stats`

For the building script I believe I modified from what's stored on crusher in  /sw/summit/ums/ums010/2022_07/warpx/2022-07-14-ascent-crusher-everything.tar.gz

Here is the final build script in attachment, which I think sets the environments quite similar to build_ascent_hip_crusher.sh that you pointed to?

Xuan

________________________________

**Comment by cyrush** [comment]
@xuanhuang1 

Thanks, I think attachment was filtered. 

There have been quite a few changes to build_ascent_hip_crusher.sh since the 2022/07/14 script, I would be good to try to use the latest script.

I deleted the bflow-stats branch, and I am going to close this PR since it was related to bflow-stats branch.

**Comment by xuanhuang1** [comment]
Hi Cyrus,

I am able to build the updated ascent with the hip script you pointed me to, but I got linking error from the example/babelflow directoeries on bflow_topo_stats branch. Any updates from the cmake side I'm missing?

[  2%] Linking CXX executable ../../../tests/blt_hip_smoke
cd /ccs/home/xuanhuang/package/ascent_crusher/ascent-crusher-build-scripts/ascent_r     epo/ascent/build_bflow_hip_script/blt/tests/smoke && /autofs/nccs-svm1_sw/crusher/s     pack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i     7tchi64s3qd/bin/cmake -E cmake_link_script CMakeFiles/blt_hip_smoke.dir/link.txt --     verbose=1
/opt/cray/pe/craype/2.7.19/bin/CC -I/opt/rocm-5.2.0/include -Wno-pass-failed    -O3      -DNDEBUG -L/opt/rocm-5.2.0/lib -lamdhip64 CMakeFiles/blt_hip_smoke.dir/blt_hip_smo     ke.cpp.o -o ../../../tests/blt_hip_smoke  /opt/rocm-5.2.0/lib/libamdhip64.so.5.2.50     200 --hip-link --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --     offload-arch=gfx90a --offload-arch=gfx1030 /opt/rocm-5.2.0/llvm/lib/clang/14.0.0/li     b/linux/libclang_rt.builtins-x86_64.a
/opt/cray/pe/cce/15.0.0/cce/x86_64/share/../bin/cce_omp_offload_linker: Unsupported      hip accelerator target: gfx1030
clang-15: error: linker command failed with exit code 255 (use -v to see invocation     )
make[2]: *** [blt/tests/smoke/CMakeFiles/blt_hip_smoke.dir/build.make:102: tests/bl     t_hip_smoke] Error 1
make[2]: Leaving directory '/autofs/nccs-svm1_home1/xuanhuang/package/ascent_crushe     r/ascent-crusher-build-scripts/ascent_repo/ascent/build_bflow_hip_script'
make[1]: *** [CMakeFiles/Makefile2:2073: blt/tests/smoke/CMakeFiles/blt_hip_smoke.d     ir/all] Error 2
make[1]: Leaving directory '/autofs/nccs-svm1_home1/xuanhuang/package/ascent_crushe     r/ascent-crusher-build-scripts/ascent_repo/ascent/build_bflow_hip_script'
make: *** [Makefile:149: all] Error 2
***@***.*** build_bflow_hip_script]$ /ccs/home/xuanhuang/package/ascent_crusher/ascent-crusher-build-scripts/ascent_repo/ascent/install_hip_script
-bash: /ccs/home/xuanhuang/package/ascent_crusher/ascent-crusher-build-scripts/ascent_repo/ascent/install_hip_script: Is a directory


Xuan


________________________________

**Comment by cyrush** [comment]
@xuanhuang1 

These errors in the excerpt don't seem to be in `example/babelflow`, is this the right set of error messages?

**Comment by xuanhuang1** [comment]
Hmm I was testing by changing the CMakeList.txt here:

if(BABELFLOW_FOUND)

add_subdirectory(babelflow/pmt)

add_subdirectory(babelflow/comp)

add_subdirectory(babelflow/iso)
endif()
https://github.com/Alpine-DAV/ascent/blob/bflow-topo-stats/src/examples/CMakeLists.txt#L23

Ascent compiles fine if I disable this part and throws the below error as I enable building these folders.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xuanhuang1** [comment]
Hi Cyrus,

Sorry to bug you again on this. This really got me confused and I wonder if you have any idea?

It does seem that the error is not from bflow directly but the message appear after I enable the babflow build directories in CMAKE.

Any thoughts would be helpful!

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Xuan ***@***.***>
Sent: Tuesday, April 11, 2023 4:06 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hmm I was testing by changing the CMakeList.txt here:

if(BABELFLOW_FOUND)

add_subdirectory(babelflow/pmt)

add_subdirectory(babelflow/comp)

add_subdirectory(babelflow/iso)
endif()
https://github.com/Alpine-DAV/ascent/blob/bflow-topo-stats/src/examples/CMakeLists.txt#L23

Ascent compiles fine if I disable this part and throws the below error as I enable building these folders.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1 Want to setup a time next week to meet and try to solve these mysteries? Are you open Tuesday 5/9 between 1- and 3 pacific?

**Comment by xuanhuang1** [comment]
Hi Cyrus,

Thank you!

Would anytime later this week work, like Thursday or Friday? I’m having a bit issue with my machine and hope to get it fixed soon…

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1 yes, I am open Friday Morning 9 - 12 pacific. 

Let me know if part of this time will work for you and I will send an webex invite.

**Comment by xuanhuang1** [comment]
Yes! can we do 9am pacific on Friday?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xuanhuang1** [comment]
Hi Cyrus,

There’s one more thing as I try to test the updated script for the entire (super)build. The mfem dependency encounters a clang build error and unfortunately the third party build&install folders were overwritten so I don’t get to compare with the previous build (probably from the older version of the script).
I wonder if you have any idea on this. I attached the mfem related error and build section here. The module list is as below:


Currently Loaded Modules:
  1) craype-x86-trento                       9) cray-dsmml/0.2.2
  2) libfabric/1.15.2.0                     10) cray-libsci/22.12.1.1
  3) craype-network-ofi                     11) PrgEnv-cray/8.3.3
  4) perftools-base/22.12.0                 12) DefApps/default
  5) xpmem/2.5.2-2.4_3.45__gd0f7936.shasta  13) cmake/3.23.2
  6) cray-pmi/6.1.8                         14) craype-accel-amd-gfx90a
  7) cce/15.0.0                             15) rocm/5.2.0
  8) craype/2.7.19                          16) cray-mpich/8.1.23



Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Xuan ***@***.***>
Sent: Monday, May 8, 2023 12:55 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Yes! can we do 9am pacific on Friday?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xuanhuang1** [comment]
Hi Xuan,

Looks like the compiler is crashing, I haven’t see that happen before.

The first thing you can try is turning off mfem – you don’t need it for your cases.

env build_mfem=false


-Cyrus

From: Xuan Huang ***@***.***>
Date: Wednesday, May 17, 2023 at 5:55 PM
To: Alpine-DAV/ascent ***@***.***>, Alpine-DAV/ascent ***@***.***>
Cc: Mention ***@***.***>, "Harrison, Cyrus D." ***@***.***>, "Petruzza, Steve Nicola Antonio [LLNL Collaborator]" ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hi Cyrus,

There’s one more thing as I try to test the updated script for the entire (super)build. The mfem dependency encounters a clang build error and unfortunately the third party build&install folders were overwritten so I don’t get to compare with the previous build (probably from the older version of the script).
I wonder if you have any idea on this. I attached the mfem related error and build section here. The module list is as below:


Currently Loaded Modules:
  1) craype-x86-trento                       9) cray-dsmml/0.2.2
  2) libfabric/1.15.2.0                     10) cray-libsci/22.12.1.1
  3) craype-network-ofi                     11) PrgEnv-cray/8.3.3
  4) perftools-base/22.12.0                 12) DefApps/default
  5) xpmem/2.5.2-2.4_3.45__gd0f7936.shasta  13) cmake/3.23.2
  6) cray-pmi/6.1.8                         14) craype-accel-amd-gfx90a
  7) cce/15.0.0                             15) rocm/5.2.0
  8) craype/2.7.19                          16) cray-mpich/8.1.23



Xuan

Sent from Mail<https://urldefense.us/v3/__https:/go.microsoft.com/fwlink/?LinkId=550986__;!!G2kpM7uM-TzIFchu!xvYXV_EA3S1neFxoVBwWb-MsEK0U4Fqef-KWxzkK_hX3QHcv3XdkiYYOxxUVPY5eBTIt9scReLpuy-80wfXEld13gcz7$> for Windows

From: Xuan ***@***.***>
Sent: Monday, May 8, 2023 12:55 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Yes! can we do 9am pacific on Friday?

Xuan

Sent from Mail<https://urldefense.us/v3/__https:/go.microsoft.com/fwlink/?LinkId=550986__;!!G2kpM7uM-TzIFchu!xvYXV_EA3S1neFxoVBwWb-MsEK0U4Fqef-KWxzkK_hX3QHcv3XdkiYYOxxUVPY5eBTIt9scReLpuy-80wfXEld13gcz7$> for Windows

**Comment by xuanhuang1** [comment]
Hi Xuan,

Update:

Nicole shared that she saw this crash when building with `cce/15.0.0`  (which is the default module)

We suggest trying:

cce/15.0.1 or cce/14.0.2

Hope this helps,

-Cyrus

From: Xuan Huang ***@***.***>
Date: Wednesday, May 17, 2023 at 5:55 PM
To: Alpine-DAV/ascent ***@***.***>, Alpine-DAV/ascent ***@***.***>
Cc: Mention ***@***.***>, "Harrison, Cyrus D." ***@***.***>, "Petruzza, Steve Nicola Antonio [LLNL Collaborator]" ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hi Cyrus,

There’s one more thing as I try to test the updated script for the entire (super)build. The mfem dependency encounters a clang build error and unfortunately the third party build&install folders were overwritten so I don’t get to compare with the previous build (probably from the older version of the script).
I wonder if you have any idea on this. I attached the mfem related error and build section here. The module list is as below:


Currently Loaded Modules:
  1) craype-x86-trento                       9) cray-dsmml/0.2.2
  2) libfabric/1.15.2.0                     10) cray-libsci/22.12.1.1
  3) craype-network-ofi                     11) PrgEnv-cray/8.3.3
  4) perftools-base/22.12.0                 12) DefApps/default
  5) xpmem/2.5.2-2.4_3.45__gd0f7936.shasta  13) cmake/3.23.2
  6) cray-pmi/6.1.8                         14) craype-accel-amd-gfx90a
  7) cce/15.0.0                             15) rocm/5.2.0
  8) craype/2.7.19                          16) cray-mpich/8.1.23



Xuan

Sent from Mail<https://urldefense.us/v3/__https:/go.microsoft.com/fwlink/?LinkId=550986__;!!G2kpM7uM-TzIFchu!xvYXV_EA3S1neFxoVBwWb-MsEK0U4Fqef-KWxzkK_hX3QHcv3XdkiYYOxxUVPY5eBTIt9scReLpuy-80wfXEld13gcz7$> for Windows

From: Xuan ***@***.***>
Sent: Monday, May 8, 2023 12:55 PM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Yes! can we do 9am pacific on Friday?

Xuan

Sent from Mail<https://urldefense.us/v3/__https:/go.microsoft.com/fwlink/?LinkId=550986__;!!G2kpM7uM-TzIFchu!xvYXV_EA3S1neFxoVBwWb-MsEK0U4Fqef-KWxzkK_hX3QHcv3XdkiYYOxxUVPY5eBTIt9scReLpuy-80wfXEld13gcz7$> for Windows

**Comment by xuanhuang1** [comment]
Hi Cyrus and Nicole,

Thanks for the update! Unfortunately neither cce/15.0.1 or cce/14.0.2 solves the clang linking error and causes the same trouble for the vtk-m build, which isn’t happening with the default 15.0.0

For now I’m back to previous module and trying to disable mfem as you mentioned. Also, just for quicker build, what’s the minimum collection of dependencies for ascent to build itself with mpi (+babelflow)?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xuanhuang1** [comment]
Update on this. After disabling mfem and cmake into a new build, another clang error appears in the make process:

/opt/cray/pe/cce/15.0.0/cce/x86_64/share/../bin/cce_omp_offload_linker: Unsupported hip accelerator target: gfx1030
clang-15: error: linker command failed with exit code 255 (use -v to see invocation)


Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Xuan ***@***.***>
Sent: Thursday, May 18, 2023 5:42 PM
To: Harrison, Cyrus ***@***.***>; ***@***.***>
Cc: Petruzza, Steve Nicola Antonio [LLNL ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hi Cyrus and Nicole,

Thanks for the update! Unfortunately neither cce/15.0.1 or cce/14.0.2 solves the clang linking error and causes the same trouble for the vtk-m build, which isn’t happening with the default 15.0.0

For now I’m back to previous module and trying to disable mfem as you mentioned. Also, just for quicker build, what’s the minimum collection of dependencies for ascent to build itself with mpi (+babelflow)?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
Hi Xuan,

Can you send me your latest script that builds babelflow and the related dependences?

I add this to the main build_ascent.sh script so we can make sure everything lines up and smooth out any build issues.

-Cyrus

From: xuanhuang1 ***@***.***>
Reply-To: Alpine-DAV/ascent ***@***.***>
Date: Thursday, May 18, 2023 at 4:43 PM
To: Alpine-DAV/ascent ***@***.***>
Cc: "Harrison, Cyrus D." ***@***.***>, State change ***@***.***>
Subject: Re: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)

Hi Cyrus and Nicole,

Thanks for the update! Unfortunately neither cce/15.0.1 or cce/14.0.2 solves the clang linking error and causes the same trouble for the vtk-m build, which isn’t happening with the default 15.0.0

For now I’m back to previous module and trying to disable mfem as you mentioned. Also, just for quicker build, what’s the minimum collection of dependencies for ascent to build itself with mpi (+babelflow)?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986><https://urldefense.us/v3/__https:/go.microsoft.com/fwlink/?LinkId=550986*3E__;JQ!!G2kpM7uM-TzIFchu!yC4ooenxda9idEBkSePwDa0Lq7U_SNIK63olanYHc0NhWPE6hg7x7c1alosA56OGPhJ3EFh7-e4FpwS2L0MHZ4p3$> for Windows

**Comment by xuanhuang1** [comment]
Sure! The changes are in build_ascent_hip.sh, starting line 403.

At the same time I tried something ugly: it looks like I can built mfem with cce 15.0.1 and the rest dependencies with cce 15.0.0. The old executable runs fine (I guess since it doesn’t use the mfem lib anyway) so I got something to run our test for. Still the new build I’m trying to make failed with the clang linking error.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by xuanhuang1** [comment]
Update on this. I’m building on frontier and was able to build develop with the script. However after merging develop into bflow-topo-stat branch the clang error occur when building.

Some environments get messed up on that bflow-topo-stat branch?

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows


From: Xuan Huang ***@***.***>
Sent: Monday, May 22, 2023 4:04:04 PM
To: Alpine-DAV/ascent ***@***.***>; Alpine-DAV/ascent ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)


Sure! The changes are in build_ascent_hip.sh, starting line 403.



At the same time I tried something ugly: it looks like I can built mfem with cce 15.0.1 and the rest dependencies with cce 15.0.0. The old executable runs fine (I guess since it doesn’t use the mfem lib anyway) so I got something to run our test for. Still the new build I’m trying to make failed with the clang linking error.



Xuan



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1  - looking at the `bflow-topo-stats` branch, I don't see any changes to the build_ascent_hip script?

Can you just email me a sh with your hip changes?

**Comment by xuanhuang1** [comment]
Ah yes I made a copy out of the repo to mess around and it didn’t get tracked. Here’s the updated script. Babelflow stuff starts at line 597 right before ascent build.

This should builds fine running directly. Once git checkout bflow-topo-stats and rebuild the issue occurs.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by xuanhuang1** [comment]
Any news with this?

Xuan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Xuan Huang ***@***.***>
Sent: Thursday, May 25, 2023 4:13:21 PM
To: Alpine-DAV/ascent ***@***.***>; Alpine-DAV/ascent ***@***.***>
Cc: Mention ***@***.***>; Harrison, Cyrus D. ***@***.***>; Petruzza, Steve Nicola Antonio [LLNL Collaborator] ***@***.***>
Subject: RE: [Alpine-DAV/ascent] Merge develop into bflow-stats (PR #1095)


Ah yes I made a copy out of the repo to mess around and it didn’t get tracked. Here’s the updated script. Babelflow stuff starts at line 597 right before ascent build.



This should builds fine running directly. Once git checkout bflow-topo-stats and rebuild the issue occurs.



Xuan



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows



________________________________

**Comment by nicolemarsaglia** [comment]
Hi Xuan,

Cyrus is out this week, and I have not been tracking this issue, so apologies if I don’t have all the details correct.

Is/was Cyrus building the babelflow-topo-stats branch on Frontier? And is this a crashing build that he was trying to fix?

Please correct me if I have any of that wrong.

If you send me the build script you are using I should be able to pick up where he left off.

Best,
Nicole

**Comment by xuanhuang1** [comment]
Hi Nicole,

Thank you for picking this up! We trying to build ascent + babelflow branch on Frontera. Currently I updated this script to build dependencies and it works with master, but once I switched to bflow-topo-stats there is an cmake error about linking clang (with various cce versions attempts).

Here is the script. Once finished I do a branch switch to rebuild ascent.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by nicolemarsaglia** [comment]
I’m not seeing an attached build script. Could try sending again? Maybe email it to me directly rather than via github: ***@***.******@***.***>

Thanks!

Best,
Nicole

**Comment by xuanhuang1** [comment]
Hmm the email address seems encrypted in this thread. I saw just a bunch of ***. Will you send me a screenshot or something (maybe txt)?

Also I wonder if a zip will work. Do you get the attachment here?

Xuan


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by nicolemarsaglia** [comment]
That's so weird! Trying replying directly via github. My email: marsaglia1@llnl.gov

**Comment by nicolemarsaglia** [comment]
Posting the script I used to build bflow-topo-stats for posterity:

```
module load cmake/3.23.2
module load PrgEnv-cray
module load cray-python
module load craype-accel-amd-gfx90a
module load rocm/5.2.0
module load cce/15.0.1
module load cray-mpich/8.1.23

export MPICH_GPU_SUPPORT_ENABLED=1
export FI_MR_CACHE_MONITOR=memhooks
export ROCFFT_RTC_CACHE_PATH=/dev/null
export ROCM_ARCH=gfx90a
export CC=$(which cc)
export CXX=$(which CC)
export FTN=$(which ftn)
export CFLAGS="-I${ROCM_PATH}/include"
export CXXFLAGS="-I${ROCM_PATH}/include -Wno-pass-failed"
export LDFLAGS="-L${ROCM_PATH}/lib -lamdhip64"
export HIPFLAGS="-I/opt/cray/pe/mpich/default/ofi/rocm-compiler/5.0/include/"
env enable_mpi=ON enable_find_mpi=OFF ./build_ascent.sh
```

**Comment by xuanhuang1** [comment]
Thank you for the update and great to know! I will try this soon!

Xuan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
