### PR TITLE
Fixes to testing scripts.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@cyrush @mclarsen Please review and merge. These are a few changes to my testing scripts. Thanks!

**Comment by danlipsa** [comment]
@cyrush @mclarsen ping. Not sure what is wrong with the CIs. Does not seem related.

**Comment by cyrush** [comment]
seems something is wrong the the spack fork or the hot copied vtk-h spack package.py

fetch tries:
```
==> Warning: No Spack mirrors are currently configured
curl: (22) The requested URL returned error: 404 Not Found
==> Fetching https://github.com/Alpine-DAV/vtk-h/releases/download/v0.5.2/vtkh.tar.gz
==> Fetching from https://github.com/Alpine-DAV/vtk-h/releases/download/v0.5.2/vtkh.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-vtk-h-0.5.2-kq5ibbtwqim66t3cq3xa7ljgigxnlw6s

```

But we need:
```
https://github.com/Alpine-DAV/vtk-h/releases/download/v0.5.2/vtkh-v0.5.2.tar.gz
```

@mclarsen  do you want me to try to heal it?

**Comment by mclarsen** [comment]
Sorry Dan, this is all my fault. I'll fix it and merge your PR.

**Comment by danlipsa** [comment]
No worries. Thanks guys!

**Pull request merged**
