### PR TITLE
Depth composite bug

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
Vtkm is handing us negative depth values which we aren't equipped to handle. This is a change of strategy that allows negative values through.

### CODE REVIEW

**Comment by nicolemarsaglia** [comment]
Issue: I'm losing legend annotations

output: 

tout_render_bounds_2d100

baseline: 
https://github.com/Alpine-DAV/ascent/blob/develop/src/tests/baseline_images/tout_render_bounds_2d100.png

diff: 
diff_tout_render_bounds_2d100

**Comment by nicolemarsaglia** [comment]
Instead of dealing with negative values when they are encountered in the image compositor, I'm dealing with them in the Image initialization by taking the abs value. Hopefully that works.

**Comment by cyrush** [comment]
Awesome, can we add a baseline check for the reproducer I added in this PR:

https://github.com/Alpine-DAV/ascent/pull/1005/

**Comment by nicolemarsaglia** [comment]
> Awesome, can we add a baseline check for the reproducer I added in this PR:
> 
> #1005

Good call. Will do!

**Review by cyrush — APPROVED** [review]
Nice work sorting this out!

**Pull request merged**
