### PR TITLE
update Ascent to use VTKm 2.0

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
Changes of note: 
*VTKm's cmake naming conventions
*Necessary updates to VTKm to Blueprint data adaptor

### CODE REVIEW

**Comment by cyrush** [comment]
@nicolemarsaglia I refactored the vtk-m  to blueprint to fix that exception you saw.

Needed to defend against cases where we want to zero-copy but its not possible b/c of the underlying vtk-m data representation.  I am still a bit puzzled as to why the specific case appeared in a field (it was saying we couldn't fetch from uniform coord array that represented a field), so their might be a larger mystery yet.

**Comment by nicolemarsaglia** [comment]
> @nicolemarsaglia I refactored the vtk-m to blueprint to fix that exception you saw.
> 
> Needed to defend against cases where we want to zero-copy but its not possible b/c of the underlying vtk-m data representation. I am still a bit puzzled as to why the specific case appeared in a field (it was saying we couldn't fetch from uniform coord array that represented a field), so their might be a larger mystery yet.

shmart shmart! looks good! I'll try to remember this when another clue to the mystery appears in six months.

**Comment by cyrush** [comment]
I updated the CI containers with vtk-m builds.
A few things I have noticed so far:

- There is some work to do on the explicit device link for static cuda builds. (vtk-m target names changed)
- For the using makefile examples we should use vtk-ms  new logic
- I saw a windows crash with scalar rendering that looks like an array of bounds issue

**Comment by cyrush** [comment]
Here is the windows crash:
```
  [==========] Running 1 test from 1 test suite.
  [----------] Global test environment set-up.
  [----------] 1 test from ascent_scalar_rendering
  [ RUN      ] ascent_scalar_rendering.test_scalar_rendering
Testing scalar  Renderingunknown file : error : SEH exception with code 0xc0000005 thrown in the test body. [D:\a\ascent\ascent\build\RUN_TESTS.vcxproj]
  [  FAILED  ] ascent_scalar_rendering.test_scalar_rendering (114 ms)
```

BabelFlow logic needs VTK-m 2.0 updates:
```
/__w/1/s/src/libs/ascent/runtimes/flow_filters/ascent_runtime_babelflow_iso.cpp:301:21: error: 'DynamicCellSet' in namespace 'vtkm::cont' does not name a type
  301 |   const vtkm::cont::DynamicCellSet &cellset = data_set.GetCellSet();
      |                     ^~~~~~~~~~~~~~
/__w/1/s/src/libs/ascent/runtimes/flow_filters/ascent_runtime_babelflow_iso.cpp:312:24: error: 'cellset' was not declared in this scope; did you mean 'close'?
  312 |   mapper->RenderCells( cellset, coords, field, renderer.GetColorTable(), cam, range );
      |                        ^~~~~~~
      |                        close
```

And this issue with build_ascent gcc, testing install with the `using-with-cmake-mpi`:

```
Checking Ascent using-with-cmake-mpi example"
...
 -- Build files have been written to: /home/runner/work/ascent/ascent/install/examples/ascent/using-with-cmake-mpi/build
[ 50%] Building CXX object CMakeFiles/ascent_mpi_render_example.dir/ascent_mpi_render_example.cpp.o
[100%] Linking CXX executable ascent_mpi_render_example
[100%] Built target ascent_mpi_render_example
./build/ascent_mpi_render_example: error while loading shared libraries: libvtkm_worklet-2.0.so.2.0: cannot open shared object file: No such file or directory
./build/ascent_mpi_render_example: error while loading shared libraries: libvtkm_worklet-2.0.so.2.0: cannot open shared object file: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by cyrush** [comment]
I solved the babelflow issue.

**Comment by cyrush** [comment]
I solved the static libs target name issue.

**Comment by cyrush** [comment]
Green :-)

**Review by cyrush — APPROVED** [review]

**Pull request merged**
