### PR TITLE
remove things that are no longer used

### PR DESCRIPTION
**Pull request by mclarsen**
@cyrush This will reduce the confusion of people trying to use old things that are no longer maintained/used.

### CODE REVIEW

**Comment by cyrush** [comment]
Sounds good, but can we keep config-build? (or just move into scripts?)
I do use this quite often.

**Comment by mclarsen** [comment]
Doesn't config-build use the host-configs?

**Comment by cyrush** [comment]
you can pass it a cmake cache file as the first arg - thats the mode that I always use it in.

**Comment by cyrush** [comment]
./config-build.sh uberenv_libs/hostname.cmake

**Review by cyrush — APPROVED** [review]
:-)

**Pull request merged**
