### PR TITLE
update cmake python logic to allow build against statically linked python

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by mclarsen** [comment]
Do downstream consumers need to link python in the dynamic case or does this only apply in the static case?

**Comment by cyrush** [comment]
they may still need to, but I think we can fix with more work to the exported cmake targets and the config-mk -- lets not merge yet

**Comment by cyrush** [comment]
yeah -- ci confirms still things to iron out.

**Comment by mclarsen** [comment]
Don't forget about the make file.

**Comment by cyrush** [comment]
closing since our CMake logic has diverged too much, see #977 for what we should salvage in the future.

**Pull request closed without merging**
