### PR TITLE
WIP: testing caching of dependencies

### PR DESCRIPTION
**Pull request by mclarsen**

### CODE REVIEW

**Comment by mclarsen** [comment]
Even a serial build takes a dump on marching cubes.

**Comment by mclarsen** [comment]
@cyrush I am not sure why vtk-h builds "seemingly" reliably in its own repo, but I cannot build it here. Every time I am getting an internal compiler error and I have tried gcc-4.8, gcc-4.9, and gcc-5. 
I was attempting to play around with caching and I have figured out how to do it while still building vtk-m and vth-h every time (cache is only 450 MB).

**Comment by cyrush** [comment]
for context, Spack defaults to build with RelWithDebugInfo, all the symbols for vtkm and vtkh overwhelmed the compilers in CI. As part of this PR, we are not building vtkm and vtkh with Release.

**Comment by cyrush** [comment]
If you are trying to rebuild vtkm + vtkh, you can also us something like:

`uberenv_libs/spack/bin/spack uninstall --dependents vtkm`

**Pull request merged**
