### PR TITLE
Il task5 filtering

### PR DESCRIPTION
**Pull request by cdl-ilight**
Delivery of the Intelligent Light's "Task 5" work for Devil Ray.
This PR contains implementations of Collection -> Collection filters in Devil Ray for:

* Threshold (Edit: Looks like this was completed in #959)
* Recenter (CellAverage / PointAverage) (Edit: Looks like this was completed in #959)
* Isosurface
* Slice
* ThreeSlice
* IsoVolume
* Clip

Work completed by myself and @BradWhitlock, I will monitor this PR for any requested changes / questions.

I've tested this code locally using the Serial, OpenMP, and Cuda execution policies.

### CODE REVIEW

**Comment by cdl-ilight** [comment]
Hey @cyrush and @brugger1, I wanted to give you guys a ping now that I see the CI has passed

**Comment by cyrush** [comment]
@cdl-ilight thanks! I am working on reviewing.

**Comment by cyrush** [comment]
Things are in great shape!

Q: Are there explicit tests for Isosurface vs Isovolume. 

For Example, I see clip 3d field cases, like:

Screen Shot 2022-12-01 at 11 45 18 AM

Is there a case that extracts the isosurface instead of isovolume?

**Comment by cdl-ilight** [comment]
@cyrush The testing for the new Isosurface (MarchingCubes) filter was done via the t_dray_extract_slice tests, this test file doesn't use Conduit baselines but you can write the blueprints out by recompiling with #define SAVE_BLUEPRINTS.

It looks like Isosuface and Isovolume are missing explicit tests of their own; this was an oversight on my part as I tested most of the functionality through the t_dray_extrace_slice and t_dray_clipfield tests.

If you'd like I can spend some time adding unit tests for these, either to this PR or as a follow-up PR.

**Comment by cyrush** [comment]
@cdl-ilight if possible to add those tests to this PR that would be very helpful. 


Also for the current tests - I think we should always save the blueprint files, but I can make that change after this PR.

**Comment by cdl-ilight** [comment]
Okay, I'll spend some time today adding tests with baselines for Isosurface and Isovolume to this PR. I've got some other things I'm wrapping up currently, but you should see something pushed up here tonight.

**Comment by cyrush** [comment]
Awesome, thanks!

**Comment by cdl-ilight** [comment]
Hey @cyrush, the new tests for those filters have been added to this branch.

Please let me know if there are any issues.

**Comment by cyrush** [comment]
@cdl-ilight  Thanks for adding those cases! We are ready to merge. 

Note: 
I tested with HIP and found some differences and one hang - but I plan to resolve those issues b/c bleeding edge hip environment introduces too many variables to control. 

 I may ping you with some specific questions in the indeterminate future if that's ok?

**Comment by cdl-ilight** [comment]
@cyrush Sure that's okay with me

**Pull request merged**
