### PR TITLE
Expressions

### PR DESCRIPTION
**Pull request by mclarsen**

### CODE REVIEW

**Review by cyrush — APPROVED** [review]
Looks good, here are the two things we talked about so I don't forget: 

*Blueprint arch knows about eles and verts vs points and cells
*Set MPI comm workspace directly for the mpi exprs test to avoid things looking like black magic

**Comment by mclarsen** [comment]
@cyrush I made the changes you asked for. Additionally, I changed:

1) runtime now gathers all actions then executes them in a specific order(queries, triggers, pipelines, scenens, extracts)
2) I slightly changed exception handling. Now, the main runtime will catch both vtkh errors, conduit errors (just a re-throw), and catching all other std::exceptions (re-throw as conduit error). This way all errors are caught and dealt with inside the `ascent.cpp` file.

**Comment by mclarsen** [comment]
resolves #97

**Review by cyrush — APPROVED** [review]
Looks good!

**Comment by cyrush** [comment]
FYI: The Travis VTK-h=off case is failing trigger tests (ascent_triggers.complex_trigger) - maybe missing guard for vtk-h enabled for this case?

https://travis-ci.org/Alpine-DAV/ascent/jobs/528476889

```
[
  
  {
    "action": "add_triggers",
    "triggers": 
    {
      "t1": 
      {
        "params": 
        {
          "condition": "magnitude(position(max(\"braid\")) - vector(0,0,0)) > 0",
          "actions_file": "/home/travis/build/Alpine-DAV/ascent/build-debug/tests/_output/complex_trigger_actions"
        }
      }
    }
  },
  
  {
    "action": "execute"
  }
]
[Error] Ascent::execute 
{
  "file": "/home/travis/build/Alpine-DAV/ascent/src/flow/flow_workspace.cpp",
  "line": 444,
  "message": "Cannot create unknown filter type: default_render"
}
```

**Pull request merged**
