### PR TITLE
Add Fides library

### PR DESCRIPTION
**Pull request by dpugmire**
Add Fides so that VTKm datasets can be written to ADIOS.

### CODE REVIEW

**Comment by cyrush** [comment]
Awesome!  I'll work to build our CI containers with Fides support.

**Comment by dpugmire** [comment]
> Awesome! I'll work to build our CI containers with Fides support.

Thanks! Let me know what I can do to help with this.

**Comment by cyrush** [comment]
Ta-da, the new container exists. 

To use it, edit this file in your fork:

https://github.com/dpugmire/ascent/blob/1bbf9184490a367278c80662797ab2a6e3427267/azure-pipelines.yml#L11

To select the following container name:

`alpinedav/ascent-ci:ubuntu-18-devel-tpls_2021-06-22-sha1bbf91`

Then we should be in business.

**Comment by dpugmire** [comment]
@mclarsen 
I think this is ready for a review now.

**Comment by dpugmire** [comment]
@cyrush 
Did I update the container thingy correctly? (I'm not really sure what you had me do -- and so not sure if this is causing the build failures)

**Review by cyrush — APPROVED** [review]

**Comment by cyrush** [comment]
Looks good, I checked the configure line in CI and Fides == on.

**Comment by dpugmire** [comment]
Thanks.
I forget what the merge process is. Do I ask someone with write access to push the button?

**Pull request merged**
