### PR TITLE
Task/move vtk h out

### PR DESCRIPTION
**Pull request by utkarshayachit**
Depends on https://github.com/Alpine-DAV/vtk-h/tree/reorg

### CODE REVIEW

**Comment by utkarshayachit** [comment]
@mclarsen this is a first pass at taking vtk-h out. I can't seem to get the CI builds working, however. Do you have any pointers? I think I updated the spack config reasonably, as it works fine locally for me, but maybe I'm missing something. If you have any clues, that'd be great.

This depends on `reorg` branch in the vtk-h repo (https://github.com/Alpine-DAV/vtk-h/tree/reorg)

**Comment by cyrush** [comment]
@utkarshayachit sorry spack isn't giving us enough bread crumbs to figure this out.
The circle ci build tests the docker path, which we have a chance to reproduce outside of the CI env. 

I can try to look into this for you tonight.

**Comment by cyrush** [comment]
@utkarshayachit as you saw, we can't update to newer spack that easily. We are going to have some support from the spack folks in ~October to move us forward. If you are interested the gory details, here is a discussion of what is needed:  https://github.com/LLNL/conduit/issues/77

**Comment by mclarsen** [comment]
I'll try to look at this as well when I get a chance

**Comment by cyrush** [comment]
I was able to fire off the a docker build, and get the resulting spack log:

```
Call Stack (most recent call first):
  /ascent/uberenv_libs/spack/opt/spack/linux-x86_64/gcc-5.4.0/cmake-3.8.2-qzlqxjpcjaz4ysakzxj2etpclg3bnkfi/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /ascent/uberenv_libs/spack/opt/spack/linux-x86_64/gcc-5.4.0/cmake-3.8.2-qzlqxjpcjaz4ysakzxj2etpclg3bnkfi/share/cmake-3.8/Modules/FindMPI.cmake:622 (find_package_handle_standard_args)
  blt/cmake/thirdparty/SetupMPI.cmake:47 (find_package)
  blt/cmake/thirdparty/SetupThirdParty.cmake:62 (include)
  blt/SetupBLT.cmake:92 (include)
  CMakeLists.txt:81 (include)
```
Looks like this its a problem detecting MPI in vtk-h.

**Comment by cyrush** [comment]
I think we will be be ok if we include MPI settings, we can try what is done in the ice-t package:

https://github.com/Alpine-DAV/ascent/blob/task/move_vtk-h_out/scripts/uberenv/packages/icet/package.py

**Comment by utkarshayachit** [comment]
ah! Cool. thanks @cyrush. That should be easy to fix. Thanks again!

**Comment by cyrush** [comment]
I think the last key, is fowarding the +mpich variant to vtkh in uberenv-alpine:

```
    #on osx, always build mpich for mpi support
    if "darwin" in platform.system().lower():
        depends_on("mpich")
        depends_on("conduit~doc~silo~python3+mpich")
    else: # else, defer to the variant
        depends_on("conduit~doc~silo~python3")
        depends_on("mpich",when="+mpich")
        depends_on("icet+mpich", when="+mpich")
        # ADD THIS:
        depends_on("vtkh+mpich", when="+mpich")
        depends_on("conduit~doc~silo~python3+mpich", when="+mpich")
```

**Comment by utkarshayachit** [comment]
@cyrush @mclarsen this is now ready for review. Thanks.

**Comment by cyrush** [comment]
@utkarshayachit 

Looks like we are past the vtk-h MPI configure issue.

I built on my mac: `python scripts/uberenv/uberenv.py -k `

And vtk-h fails due to missing tbb info when using vtkm. 

I get several pages of errors like the following:

```
      typeinfo for tbb::interface9::internal::start_for<tbb::blocked_range<vtkm::cont::internal::IteratorFromArrayPortal<vtkm::exec::internal::ArrayPortalZip<vtkm::Pair<vtkm::worklet::EdgeInterpolation, int>, vtkm::cont::internal::ArrayPortalFromIterators<vtkm::worklet::EdgeInterpolation*, void>, vtkm::cont::internal::ArrayPortalFromIterators<int*, void> > > >, tbb::interface9::internal::quick_sort_pretest_body<vtkm::cont::internal::IteratorFromArrayPortal<vtkm::exec::internal::ArrayPortalZip<vtkm::Pair<vtkm::worklet::EdgeInterpolation, int>, vtkm::cont::internal::ArrayPortalFromIterators<vtkm::worklet::EdgeInterpolation*, void>, vtkm::cont::internal::ArrayPortalFromIterators<int*, void> > >, vtkm::cont::internal::WrappedBinaryOperator<bool, vtkm::cont::internal::KeyCompare<vtkm::worklet::EdgeInterpolation, int, vtkm::worklet::EdgeInterpolation::LessThanOp> > >, tbb::auto_partitioner const> in Clip.cpp.o
      typeinfo for tbb::interface9::internal::flag_task in Clip.cpp.o
      typeinfo for tbb::interface9::internal::start_for<tbb::interface9::internal::quick_sort_range<vtkm::cont::internal::IteratorFromArrayPortal<vtkm::exec::internal::ArrayPortalZip<vtkm::Pair<vtkm::worklet::EdgeInterpolation, int>, vtkm::cont::internal::ArrayPortalFromIterators<vtkm::worklet::EdgeInterpolation*, void>, vtkm::cont::internal::ArrayPortalFromIterators<int*, void> > >, vtkm::cont::internal::WrappedBinaryOperator<bool, vtkm::cont::internal::KeyCompare<vtkm::worklet::EdgeInterpolation, int, vtkm::worklet::EdgeInterpolation::LessThanOp> > >, tbb::interface9::internal::quick_sort_body<vtkm::cont::internal::IteratorFromArrayPortal<vtkm::exec::internal::ArrayPortalZip<vtkm::Pair<vtkm::worklet::EdgeInterpolation, int>, vtkm::cont::internal::ArrayPortalFromIterators<vtkm::worklet::EdgeInterpolation*, void>, vtkm::cont::internal::ArrayPortalFromIterators<int*, void> > >, vtkm::cont::internal::WrappedBinaryOperator<bool, vtkm::cont::internal::KeyCompare<vtkm::worklet::EdgeInterpolation, int, vtkm::worklet::EdgeInterpolation::LessThanOp> > >, tbb::auto_partitioner const> in Clip.cpp.o
      ...
```
It looks like we are passing TBB to VTK-h, so not sure what the issue is.

**Comment by utkarshayachit** [comment]
@cyrush I'll track it down. thanks.

**Comment by utkarshayachit** [comment]
@cyrush I've pushed a change to vtkh (https://github.com/Alpine-DAV/vtk-h/commit/db593b9a3f32a2052ef0d76ad4986c77f523f7fe)

Can you give it  a try please? spack doesnt' seem to work for me at all on my mac. it's failing building Python even before it gets to the vtk-h part so I can't test it.

**Comment by cyrush** [comment]
tpls built, however ascent fails due to rpath issue related to TBB

```
[  1%] Built target gtest
[  2%] Built target gtest_main
[  3%] Built target fruit
[  5%] Built target blt_mpi_smoke
[  6%] Built target blt_fruit_smoke
[  7%] Built target blt_gtest_smoke
[  8%] Built target lodepng
[ 13%] Built target flow
[ 22%] Built target ascent
[ 23%] Linking CXX shared library ../lib/libascent_par.dylib
ld: file not found: @rpath/libtbb.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libascent_par.dylib] Error 1
make[1]: *** [ascent/CMakeFiles/ascent_par.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by cyrush** [comment]
@utkarshayachit to use VTKm with TBB -- we found that had to link to TBB (the exported targets from VTKm didn't work). 

In VTK-h, I can see you are trying to solve this by linking PRIVATE to a small lib, that itself links to tbb via  INTERFACE. That looks like a good solution to me, one I would expect to work with CMake 3.8.

That said, it still seems that tbb somehow needs to be a PUBLIC dependency of ascent.  (Maybe VTKm is doing something that undermines this careful dance)

What we didn't do in Ascent, (but should have and is supported by BLT) is define tbb as a dep when we call blt_register_library. 

If we do that for vtkh, that would eliminate the target includes and target link libs calls in vtkh and make everything work.

I think we would still have to find TBB in ascent, given how TBB is leaking out of VTKm (and then likley VTKh since its relying on VTK's imported targets) But the same strategy would work -- If tbb is enabled, we can pass tbb  as a dep for blt_register_library(vtkh) in ascent.

Sorry I don't have many cycles this week (an important week !) to help demonstrate this.

**Comment by utkarshayachit** [comment]
thanks for you help @cyrush. BTW, what MacOS and Xcode are you using? I tried 3 different macs with different oses and `python scripts/uberenv/uberenv.py -k` keeps failing for me long before it gets to vtkm/vtkh. If I can reproduce it, I can track it down.

**Comment by cyrush** [comment]
@utkarshayachit , i am on OSX 10.11.6.  I am using XCode 7.3 clang with gfortran from here: https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

If python is the issue, try passing:

`python scripts/uberenv/uberenv.py -k --spec %clang~python`

**Comment by cyrush** [comment]
@utkarshayachit  working on adding travis and uberenv to vtk-h so we can test it stand alone.

Also I think have things working with respect to tbb, keeping vtk-h closer to how alpine's build system works.  I'll push this to another branch on vtk-h.

**Comment by cyrush** [comment]
almost have this working on with my vtk-h reorg branch, need to track down a stray `-ltbb`

**Comment by utkarshayachit** [comment]
oh great! Thanks a lot, @cyrush. I've been in a meeting all day today (and will be tomorrow to). thanks again.

**Comment by utkarshayachit** [comment]
btw, I managed to build with no issues using just the vtk-h/reorg and this branch with ` python scripts/uberenv/uberenv.py -k --spec %clang~python~doc` [1] with no issues. So the rpath tbb issue you were seeing is suspect. Something else is gimped there esp. since the `ascent` target didn't have an issue, only ascent_par did. 

[1] that was after additional fixes to the package.py to remove accidental dependencies on `python` even when python was disabled.

**Comment by mclarsen** [comment]
We need to update cmake to respect that VTK-h is technically an optional component, although highly recommended, or we can make it required, because without it the default runtime can't function.

While I am thinking about it. HDF5 is optional as well, but this is not currently respected because the Relay filters are always included.

I can try to tackle these with I finish the first pass at the docs.

**Comment by mclarsen** [comment]
Ignore the first part about vtkh, but i'll still look into the HDF5 stuff.

**Comment by cyrush** [comment]
ok, I worked everything out -- a lot of chasing my tail, but at least we now have a CI setup & automated builds of tpls for vtk-h as well :-)

Basically, TBB_DIR wasn't being passed when spack was building vtk-h. That was the source of the rpath mystery and of the dangling `-ltbb`s

This is now building with my branch of vtk-h (which is a branch off of @utkarshayachit's, that I hope we can merge into his, and finally into master (or develop?))


I also culled unused ice-t stuff,  got rid of project wide include for tpls, and removed some unnecessary tpl smoke tests.

**Comment by cyrush** [comment]
@utkarshayachit @mclarsen 
worked out all of the vtk-h build issues, we have cuda support again. 

We still need to merge the vtk-h reorg branch, then as part of this PR, we can update spack to point to vtk-h master and close out this reorg.

**Comment by mclarsen** [comment]
Its unclear why this is failing to build vtkh.

**Comment by mclarsen** [comment]
Circle CI is experiencing an internal compiler error trying to use g++ on vtkm

**Pull request merged**
