### PR TITLE
Fix/various issues

### PR DESCRIPTION
**Pull request by mclarsen**

### CODE REVIEW

**Review by cyrush — APPROVED** [review]

**Comment by cyrush** [comment]
@mclarsen hola is hanging b/c mesh bp verify is failing on at least one of the ranks, causing that MPI task to crash and the others to wait for eternity

**Comment by cyrush** [comment]
i understand the hola issue, my spack changes made conduit 0.3.1 build again, instead of conduit@master

**Comment by mclarsen** [comment]
@cyrush I had to resolve the undefined symbol to register filter that occurring when vtkh was off and python wanted to see register_filter. Instead of a quick fix, I am going to compile the ascent runtime without vtkh. To support this the right way, I will need to change some of the tests to look at a new `about` variable that indicates if vtkh is enabled.

**Comment by cyrush** [comment]
looks like its still picking up wrong conduit for the main case, perhaps it has to do with +mfem

**Comment by cyrush** [comment]
mfem requires conduit version 0.3.1:, but spec asked for master, 

I thought the mfem constraint was 0.3.1 or greater, but obviously something is wrong  -- I'll try to fix this soon.

**Comment by mclarsen** [comment]
I'm out during the day today but I'll finish my runtime changes tonight. My
goal is to get this merged this weekend as it clears a lot of issues

**Comment by cyrush** [comment]
I believe the fix is easy, I’ll try to push something tonight




On September 8, 2018 at 2:30:25 PM PDT, Matt Larsen <notifications@github.com> wrote:
I'm out during the day today but I'll finish my runtime changes tonight. My
goal is to get this merged this weekend as it clears a lot of issues

**Comment by mclarsen** [comment]
@cyrush Do the ascent runtime changes look ok to you?

**Comment by mclarsen** [comment]
This allows us to test extracts without having to compile in vtkm or vtkh

**Comment by cyrush** [comment]
glanced at the changes -- looks good to me!

**Comment by mclarsen** [comment]
OK. We be green again.

**Comment by cyrush** [comment]
Nice, thanks for tackling all of those issues!

**Pull request merged**
