### PR TITLE
WIP: Pull packages from oliver_parallel.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by mclarsen** [comment]
I have a branch that updated to the newer version of vtkm in both ascent and vtkh. `task/new_new_vtkm` is the branch. As soon as their branch is merged with vtkm, I can start merging those branches.

**Comment by danlipsa** [comment]
Thanks Matt, this updates vtk-h as well, and oliver_parallel is rebased on master so probably we'll have some conflicts - we'll have to sync-up. I'll start looking at integrating the serial contour tree in here as well.

**Comment by danlipsa** [comment]
@mclarsen Can you point me to your branches? Its not clear to me what do I need to change in ascent once I updated vtk-h. Thanks!

**Comment by mclarsen** [comment]
https://github.com/Alpine-DAV/ascent/tree/task/new_new_vtkm
https://github.com/Alpine-DAV/vtk-h/tree/task/new_new_vtkm

I have not update the spack builds yet.

**Comment by danlipsa** [comment]
@cyrush @mclarsen All ascent tests (61 of them) pass on my machine with SERIAL enabled on both vtkh and ascent. Should we try to merge vtkh and ascent?

**Comment by mclarsen** [comment]
merged in another pr

**Pull request closed without merging**
