### PR TITLE
rewrite MakeTestData to remove file dependency

### PR DESCRIPTION
**Pull request by nicolemarsaglia**
Include vtkm functions to make data sets. Rewrite tests to use functions rather than rely on vtk-m's MakeTestData.hxx file.

### CODE REVIEW

**Comment by cyrush** [comment]
Looks good! 

One suggestion:  - Can we change `src/tests/vtkh/t_test_utils.hpp` to `src/tests/vtkh/t_vtkh_test_utils.hpp`?

Just so it's easier to discern its role in the future?

**Comment by cyrush** [comment]
Sorry, let's do:

`src/tests/vtkh/t_vtkm_test_utils.hpp`

**Comment by nicolemarsaglia** [comment]
No problem, good suggestion!

**Review by cyrush — APPROVED** [review]
Looks good, feel free to merge.

Thanks!

**Pull request merged**
