### PR TITLE
tutorial reorg

### PR DESCRIPTION
**Pull request by cyrush**
will also address #385

### CODE REVIEW

**Comment by mclarsen** [comment]
One more thing we need to do is update the vtkm spack package + update the hashes so we are using the vtkm 1.5 release. Also, test with cuda. I can do a build tonight.

**Review by mclarsen — APPROVED** [review]
I looked through the 175 files and 49 commits. Looks good to me

**Comment by cyrush** [comment]
@mclarsen thanks! I still  have a few docker tweaks, then I'll merge. 
I suggest we use another branch to do the spack updates, this one is getting big.

**Comment by mclarsen** [comment]
resolves #395

**Pull request merged**
