### PR TITLE
add test and fix for side gen wo fields, resolves #1260

### LINKED ISSUE #1260: Polyhedral mesh executions fail when no solution is present
The following example creates a mesh of a single tetrahedron using the general polyhedral indexing format. It should then render a mesh image and extract an hdf5 file. What happens instead is:

```
[Error] Ascent::execute
file: conduit_node.cpp
line: 14084
message:
Cannot access non-existent child "fields" from Node([0])
```

it is looking for solution fields even though none are requested in the actions.

```
  std::vector<double> xvert = {0.0, 1.0, 0.0, 0.0};
  std::vector<double> yvert = {0.0, 0.0, 0.0, 1.0};
  std::vector<double> zvert = {1.0, 0.0, 0.0, 0.0};
  conduit::Node       mesh;
  mesh["coordsets/coords/type"] = "explicit";
  mesh["coordsets/coords/values/x"].set_external(xvert);
  mesh["coordsets/coords/values/y"].set_external(yvert);
  mesh["coordsets/coords/values/z"].set_external(zvert);

  std::vector<std::int32_t> poly_face_conn = {
      0,1,3,  // face 0
      1,2,3,  // face 1
      2,0,3,  // face 2
      0,2,1   // face 3
  };
  std::vector<std::int32_t> poly_face_sizes   = {3, 3, 3, 3};
  std::vector<std::int32_t> poly_face_offsets = {0, 3, 6, 9};
  std::vector<std::int32_t> poly_cell_conn    = {0, 1, 2, 3};
  std::vector<std::int32_t> poly_cell_sizes   = {4};
  std::vector<std::int32_t> poly_cell_offsets = {0};

  mesh["topologies/topo/type"]              = "unstructured";
  mesh["topologies/topo/elements/shape"]    = "polyhedral";
  mesh["topologies/topo/subelements/shape"] = "polygonal";
  mesh["topologies/topo/coordset"]          = "coords";
  mesh["topologies/topo/elements/connectivity"].set_external(poly_cell_conn);
  mesh["topologies/topo/elements/sizes"].set_external(poly_cell_sizes);
  mesh["topologies/topo/elements/offsets"].set_external(poly_cell_offsets);
  mesh["topologies/topo/subelements/connectivity"].set_external(poly_face_conn);
  mesh["topologies/topo/subelements/sizes"].set_external(poly_face_sizes);
  mesh["topologies/topo/subelements/offsets"].set_external(poly_face_offsets);

  ascent::Ascent ascent_viewer;
  conduit::Node  ascent_opts;
  ascent_viewer.open(ascent_opts);
  ascent_viewer.publish(mesh);

  conduit::Node actions;

  // declare an action to create a .png render
  conduit::Node& add_actions = actions.append();
  add_actions["action"]      = "add_scenes";
  conduit::Node& scenes      = add_actions["scenes"];
  scenes["s1/plots/p1/type"] = "mesh";
  scenes["s1/image_prefix"]  = "single_tet_poly_mesh_render";

  // declare an action to create a mesh extraction to hdf5
  conduit::Node& add_extracts    = actions.append();
  add_extracts["action"]         = "add_extracts";
  conduit::Node& extracts        = add_extracts["extracts"];
  extracts["e0/type"]            = "relay";
  extracts["e0/params/path"]     = "single_tet_poly_mesh_extract";
  extracts["e0/params/protocol"] = "blueprint/mesh/hdf5";

  ascent_viewer.execute(actions);
  ascent_viewer.close();
```

If I insert some dummy data, then the mesh render succeeds,

```
  std::vector<double> ones(xvert.size(), 1.0);
  mesh["fields/dummy/association"] = "vertex";
  mesh["fields/dummy/topology"] = "topo";
  mesh["fields/dummy/values"].set_external(ones);
```

 The same test code but using a tetrahedral type indexing (not the general polyhedral) like the following works as expected and correctly renders the mesh.

```
  std::vector<double> xvert = {0.0, 1.0, 0.0, 0.0};
  std::vector<double> yvert = {0.0, 0.0, 0.0, 1.0};
  std::vector<double> zvert = {1.0, 0.0, 0.0, 0.0};
  std::vector<int>    conn  = {0, 1, 2, 3};
  conduit::Node       mesh;
  mesh["coordsets/coords/type"] = "explicit";
  mesh["coordsets/coords/values/x"].set_external(xvert);
  mesh["coordsets/coords/values/y"].set_external(yvert);
  mesh["coordsets/coords/values/z"].set_external(zvert);
  mesh["topologies/topo/type"]           = "unstructured";
  mesh["topologies/topo/elements/shape"] = "tet";
  mesh["topologies/topo/coordset"]       = "coords";
  mesh["topologies/topo/elements/connectivity"].set_external(conn);
```

### PR DESCRIPTION
**Pull request by cyrush**
resolves #1260 by calling correct variant of gen side when no fields are present

### CODE REVIEW

**Review by nicolemarsaglia — COMMENTED** [review]
Looks good! Just need the baseline image.

**Comment by cyrush** [comment]
@nicolemarsaglia good catch, thanks!

**Comment by cyrush** [comment]
Again hitting space limits for azure:

```
-- Set runtime path of "/__w/1/s/install/utilities/ascent/ascent_about" to ""
-- Installing: /__w/1/s/install/utilities/ascent/ascent_about_mpi
-- Set runtime path of "/__w/1/s/install/utilities/ascent/ascent_about_mpi" to ""
-- Installing: /__w/1/s/install/utilities/ascent/replay/replay_ser
-- Set runtime path of "/__w/1/s/install/utilities/ascent/replay/replay_ser" to ""
-- Installing: /__w/1/s/install/utilities/ascent/replay/replay_mpi
-- Set runtime path of "/__w/1/s/install/utilities/ascent/replay/replay_mpi" to ""
-- Installing: /__w/1/s/install/utilities/ascent/replay/yaml2json
-- Set runtime path of "/__w/1/s/install/utilities/ascent/replay/yaml2json" to ""
-- Installing: /__w/1/s/install/utilities/ascent/replay/json2yaml
-- Set runtime path of "/__w/1/s/install/utilities/ascent/replay/json2yaml" to ""
-- Installing: /__w/1/s/install/utilities/ascent/holo_compare/holo
CMake Error at utilities/holo_compare/cmake_install.cmake:52 (file):
  file INSTALL cannot copy file "/__w/1/s/build/utilities/holo_compare/holo"
  to "/__w/1/s/install/utilities/ascent/holo_compare/holo": No space left on
  device.
Call Stack (most recent call first):
  utilities/cmake_install.cmake:62 (include)
  cmake_install.cmake:67 (include)

```

**Comment by cyrush** [comment]
Merging, we are right on the bubble with disk space for all features + cuda + static. We may have to trim our static test cases.

**Pull request closed without merging**
