### PR TITLE
Adding streaming statistics to task based feature detection algorithm

### PR DESCRIPTION
**Pull request by spetruzza**
Adding computation of statistics of features extracted by the task based parallelmergetree algorithm.
This PR adds also two dependencies (talass and streamstat) with their spack packages to the build (when building with babelflow). @xuanhuang1

### CODE REVIEW

**Comment by cyrush** [comment]
@spetruzza looks like BLT submodule was accidentally updated in your branch. It's easily to do this on accident when switching between branches, so the check helps us avoid surprises. 
Given this, can you remove the BLT changes? 

I will have to rebuild docker containers with new TPLS as well, then we can test in CI. 

I am prepping to start container and spack updates next week.

**Comment by cyrush** [comment]
@spetruzza looks like BLT submodule was accidentally updated in your branch. It's easily to do this on accident when switching between branches, so the check helps us avoid surprises. 
Given this, can you remove the BLT changes? I

I will have to rebuild docker containers with new TPLS as well, then we can test in CI. 

I am prepping to start container and spack updates next week.

**Comment by cyrush** [comment]
@xuanhuang1  @spetruzza  I have an updated container for babelflow, it should have the latest version (`1.1.0`) ?  and the two new dependent libs (talass and streamstat).

Seems like we are hitting a compile error in `ascent_runtime_babelflow_pmt`

```
2022-09-07T00:04:37.0116118Z /__w/1/s/src/ascent/runtimes/flow_filters/ascent_runtime_babelflow_pmt.cpp:42:10: fatal error: BabelFlow/DefGraphConnector.h: No such file or directory
2022-09-07T00:04:37.0117671Z  #include "BabelFlow/DefGraphConnector.h"
2022-09-07T00:04:37.0118223Z           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-09-07T00:04:37.0118726Z compilation terminated.
2022-09-07T00:04:37.0147201Z ascent/CMakeFiles/ascent_mpi.dir/build.make:915: recipe for target 'ascent/CMakeFiles/ascent_mpi.dir/runtimes/flow_filters/ascent_runtime_babelflow_pmt.cpp.o' failed
2022-09-07T00:04:37.0154927Z make[2]: *** [ascent/CMakeFiles/ascent_mpi.dir/runtimes/flow_filters/ascent_runtime_babelflow_pmt.cpp.o] Error 1
2022-09-07T00:04:37.0156681Z make[1]: *** [ascent/CMakeFiles/ascent_mpi.dir/all] Error 2
```

Any ideas what we should try next?

**Comment by xuanhuang1** [comment]
Hi Cyrus,

I believe the current streaming stats branch work should be built with parallelmergetree 1.0.2 and babelflow 1.0.1 (required by that parallelmergetree version in spack). This is the config I got from Sergei and I have not tried the newer version of babelflow.

I would always add spec ***@***.******@***.***> for my tests builds, so for this issue I’m guessing it’s pulling the wrong pmt package. I’m looking at specifying the version through  uberenv config, but I also realize you made some changes to merge the dependencies into ascent’s package.

What’s the best way to force a fixed parallelmergetree package version (and thus the babelflow version) for ascent now?

Xuan


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
If we need `babelflow@1.0.1` and `pmt 1.0.2` I can put those constraints in the ascent spack package. However pmt 1.0.2 is a few versions old. I feel like those newer versions were for ascent? Are we going to see an issue with other babelflow stuff in ascent if we use older version?

**Comment by xuanhuang1** [comment]
We are figuring out if we can just update those. As far as I know there should be some newer version of pmt that works with current babelflow. There are some modification in the other two dependencies for ascent integration as well, so I’m asking Sergei and see if he picked up the older pmt+babelflow for any specific reason.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1 thanks, let me know when you have an idea for the path forward. 
Ideally we get everything working the the latest releases and move forward from there to re-enable CI testing.

**Comment by xuanhuang1** [comment]
Hi Cyrus,

I'm trying to update the packages for this branch now and encountered a build issue from raja, probably from a recent update from another branch?

Do you have any idea how to get around it?

==> Installing raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr
==> No binary for raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr found: installing from source
==> Using cached archive: /home/xuanhuang/packages/ascent_stats_test/ascent/_uberenv_build_bflow1.1.1/spack/var/spack/cache/_source-cache/git//LLNL/RAJA.git/v2022.03.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> raja: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

177 errors found in build log:
     254                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4
             kxix22xt2lgfxflhxanr/spack-src/include/RAJA/policy/tensor/arch_impl.hpp:35,
     255                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4
             kxix22xt2lgfxflhxanr/spack-src/include/RAJA/policy/tensor.hpp:23,
     256                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4
             kxix22xt2lgfxflhxanr/spack-src/include/RAJA/RAJA.hpp:67,
     257                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4
             kxix22xt2lgfxflhxanr/spack-src/examples/memoryManager.hpp:11,
     258                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4
             kxix22xt2lgfxflhxanr/spack-src/examples/tut_matrix-multiply.cpp:13:
     259     /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr/s
             pack-src/include/RAJA/policy/tensor/arch/avx512/avx512_int32.hpp: In member function 'RA
             JA::expt::Register<int, RAJA::expt::avx512_register>::self_type& RAJA::expt::Register<in
             t, RAJA::expt::avx512_register>::load_packed(const element_type*)':
  >> 260     /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr/s
             pack-src/include/RAJA/policy/tensor/arch/avx512/avx512_int32.hpp:137:19: error: '_mm512_
             loadu_epi32' was not declared in this scope; did you mean '_mm512_load_epi32'?
     261       137 |         m_value = _mm512_loadu_epi32(ptr);
     262           |                   ^~~~~~~~~~~~~~~~~~
     263           |                   _mm512_load_epi32

...

See build log for details:
  /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr/spack-build-out.txt

==> Warning: Skipping build of uberenv-ascent-develop-eb4syyiztokdbzjmv6rdlj3hnri4rmgn since raja-2022.03.0-t4yesnezend4kxix22xt2lgfxflhxanr failed


Xuan
________________________________

**Comment by cyrush** [comment]
@xuanhuang1  the latest CI container stack was built from develop on 10/17.

Can you try merging develop into your branch to pick up the updated spack recipes? 

There are many more changes coming with the refactor in: #944, which I am working to merge in the next two weeks.

**Comment by xuanhuang1** [comment]
I was able to auto-merge develop with some minor babelflow cmake setting conflicts. However, the raja spack install error persists. So currently I'm falling back to a previous commit in May for a stable source code version, and that seems fine for updating ascent_babelflow itself. Testing on crusher may be a problem though since I'm not able to verify with the current version.

Anything else you'd recommend to try?


Xuan
________________________________

**Comment by cyrush** [comment]
@xuanhuang1 lets get the code changes in without the CI changes and I'll work through any spack issues after we merge. 

So, lets update the PR to skip any changes to `azure-pipelines.yml` and I'll merge.

**Comment by xuanhuang1** [comment]
I made a merge at bflow-stats branch with azure-pipelines.yml kept the same as in develop.

Please let me know how things go!

Xuan
________________________________

**Comment by xuanhuang1** [comment]
There seems to be a small typo at camp version string and I deleted the ` after merge:

version("2022.10.1`", sha256="2d12f1a46f5a6d01880fc075cfbd332e2cf296816a7c1aa12d4ee5644d386f02")
https://github.com/Alpine-DAV/ascent/commit/4fb673aa210ba8022111e061ef71ef12db6d110b#diff-4e1962a2987db876a1bb4e15771bf7520363275028a3ee340acf67b6eb6e53caR42
[https://opengraph.githubassets.com/c56a08b382fb77403bad628057361976e133a031809531c50f5ed3b6009f8ae1/Alpine-DAV/ascent/commit/4fb673aa210ba8022111e061ef71ef12db6d110b]<https://github.com/Alpine-DAV/ascent/commit/4fb673aa210ba8022111e061ef71ef12db6d110b#diff-4e1962a2987db876a1bb4e15771bf7520363275028a3ee340acf67b6eb6e53caR42>
update camp to 2022.10.1 (#1047) · ***@***.***<https://github.com/Alpine-DAV/ascent/commit/4fb673aa210ba8022111e061ef71ef12db6d110b#diff-4e1962a2987db876a1bb4e15771bf7520363275028a3ee340acf67b6eb6e53caR42>
A flyweight in situ visualization and analysis runtime for multi-physics HPC simulations - update camp to 2022.10.1 (#1047) · ***@***.***
github.com

The raja error is still there...

cmd:
***@***.***:~/packages/ascent_stats_test/ascent_update/ascent$ python3 ./scripts/uberenv/uberenv.py --spec="+babelflow~dray~doc~cuda~python ^parallelmergetree" --prefix="_uberenv_build"

error log:
==> Using cached archive: /home/xuanhuang/packages/ascent_stats_test/ascent_update/ascent/_uberenv_build/spack/var/spack/cache/_source-cache/git//LLNL/RAJA.git/v2022.03.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> raja: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

177 errors found in build log:
     254                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/incl
             ude/RAJA/policy/tensor/arch_impl.hpp:35,
     255                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/incl
             ude/RAJA/policy/tensor.hpp:23,
     256                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/incl
             ude/RAJA/RAJA.hpp:67,
     257                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/exam
             ples/memoryManager.hpp:11,
     258                      from /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/exam
             ples/tut_vertexsum-coloring.cpp:14:
     259     /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/include/RAJA/policy/tensor
             /arch/avx512/avx512_int32.hpp: In member function 'RAJA::expt::Register<int, RAJA::expt::avx512_register>::self_type& RAJA:
             :expt::Register<int, RAJA::expt::avx512_register>::load_packed(const element_type*)':
  >> 260     /tmp/xuanhuang/spack-stage/spack-stage-raja-2022.03.0-cg4cyrv3bmyllyb7hcktxdmp2k2a7fmj/spack-src/include/RAJA/policy/tensor
             /arch/avx512/avx512_int32.hpp:137:19: error: '_mm512_loadu_epi32' was not declared in this scope; did you mean '_mm512_load
             _epi32'?
     261       137 |         m_value = _mm512_loadu_epi32(ptr);
     262           |                   ^~~~~~~~~~~~~~~~~~
     263           |                   _mm512_load_epi32

Xuan
________________________________

**Comment by cyrush** [comment]
Thanks for catching that! I haven't had a chance to rebuild the ci containers yet.

**Comment by cyrush** [comment]
@xuanhuang1 I updated the containers in #1059 

`alpinedav/ascent-ci:ubuntu-18.04-devel-tpls_2022-12-01-sha22e69c`

Now has babelflow 1.1.0 and should have the other changes. 


I did try to test w/ babelflow, however the babelflow example failed to include `<mpidummy.h>`.

Can you try building in the container above and we can create a PR to resolve this issue?
That should avoid any RAJA issues you are seeing when you try to build.

**Comment by xuanhuang1** [comment]
I’m not really familiar with the ci container here, so can you share with me the instructions to build and test this?

As for the include error itself I’m guessing it’s due to mpi not enabled properly.

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1 we have many tests related to MPI, I think this is is specific to the babelflow integration. 

If you have docker, you can use:

```
docker run -it alpinedav/ascent-ci:ubuntu-18.04-devel-tpls_2022-12-01-sha22e69c
```

Then inside the shell:

```
. s_env.sh 
./clone.sh
cd ascent
cp /uberenv_libs/*cmake . 
./config-build.sh buildkitsandbox-linux-ubuntu18.04-zen-gcc\@7.5.0-ascent-s24shbaptwzchmisjlsnxxzbbmlzzdjo.cmake 
cd build-debug
make
```

Here is the error I hit:
```
[100%] Building CXX object examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/ascent_babelflow_example.cpp.o
/ascent/src/examples/babelflow/pmt/ascent_babelflow_example.cpp:14:10: fatal error: mpidummy.h: No such file or directory
 #include <mpidummy.h>
          ^~~~~~~~~~~~
compilation terminated.
examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/build.make:75: recipe for target 'examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/ascent_babelflow_example.cpp.o' failed
make[2]: *** [examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/ascent_babelflow_example.cpp.o] Error 1
CMakeFiles/Makefile2:3899: recipe for target 'examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/all' failed
make[1]: *** [examples/babelflow/pmt/CMakeFiles/ascent_babelflow_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Building CXX object examples/proxies/laghos/CMakeFiles/laghos_mpi.dir/laghos.cpp.o
[100%] Building CXX object examples/proxies/laghos/CMakeFiles/laghos_mpi.dir/laghos_solver.cpp.o
[100%] Linking CXX executable laghos_mpi
[100%] Built target laghos_mpi
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

```

Alternately, for the babelflow work you don't need RAJA. You can can skip building RAJA with spack.

**Comment by xuanhuang1** [comment]
Thanks! I’m looking at the code and looks like it hits that line because #ifdef ASCENT_MPI_ENABLED is somehow false. Will you also point me to the file which sets that bool for babelflow? I don’t seem to find mpi related complement for babelflow in azure-pipelines.yml<https://github.com/Alpine-DAV/ascent/blob/develop/azure-pipelines.yml> (L183 ubuntu_18_shared_py_cxx14_bflow sets gcc only?)… Is it specified in the docker container?

Also how do I disable raja in spack build? I tried ~raja in cmd line but uberenv is still installing it

***@***.***:~/packages/ascent_stats_test/ascent_update/ascent$ python3 ./scripts/uberenv/uberenv.py --spec="+babelflow~raja~dray~doc~cuda~python ^parallelmergetree" --prefix="_uberenv_build"



Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
@xuanhuang1 I see, `ASCENT_MPI_ENABLED` will never be defined in client code. The mpi and non mpi version share the headers and the versioned is selected by what is linked.

In this case, babelflow support should only ever be on when MPI is on (the examples link to `ascent_mpi`) So I think the right path is to simply include MPI unconditionally in this example. 

To build w/o RAJA -- You should only need `~dray~raja`, which you are using. So I am not sure why it is still trying to build RAJA, I'll take a look.

**Comment by xuanhuang1** [comment]
Ah yeah I should have made it clear earlier. Babelflow always depends on mpi thus a non mpi version is probably going to be problematic.


Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cyrush** [comment]
Makes sense, I can make that change in a PR -- sound good?

**Comment by xuanhuang1** [comment]
Yes please. Thank you!

Xuan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request merged**
