### PR TITLE
initial mfem support

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
in travis, hypre is failing to build with unresolved symbols that look like they are from lapack

```
 Making lib ...
     822    make[1]: Entering directory `/tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/lib'
     823    Building libHYPRE.so ...
     824    /usr/bin/mpic++ -shared -o libHYPRE-2.14.0.so /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/FEI_mv/fei-hypre/*.o  /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/IJ_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/distributed_ls/Euclid/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/distributed_ls/ParaSails/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/distributed_ls/pilut/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/distributed_matrix/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/krylov/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/matrix_matrix/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/multivector/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/parcsr_ls/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/parcsr_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/parcsr_block_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/seq_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/sstruct_ls/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/sstruct_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/struct_ls/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/struct_mv/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/utilities/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/blas/*.o /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/lapack/*.o   -L/usr/lib  -lopenblas -L/usr/lib  -lopenblas -lstdc++ -lm       -Wl,-soname,libHYPRE-2.14.0.so -Wl,-z,defs
     825    /tmp/travis/spack-stage/spack-stage-xIx9BT/hypre-2.14.0/src/distributed_ls/ParaSails/ParaSails.o: In function `ComputeValuesSym':
  >> 826    ParaSails.c:(.text+0xa76): undefined reference to `dpotrf_'
  >> 827    ParaSails.c:(.text+0xab1): undefined reference to `dpotrs_'
```

**Comment by mclarsen** [comment]
@cyrush The travis tests are passing except the one without vtkm for some python reason.

**Comment by mclarsen** [comment]
I am also starting to write a data adapter for mfem. I keep running into the problem that mfem does not have mpi headers hidden : `include/mfem/general/globals.hpp:19:17: fatal error: mpi.h: No such file or directory`. The config file in mfem is defining this. Not sure if we should just add the mpi dependency if we compile with MFEM and MPI.

**Comment by mclarsen** [comment]
I guess that would not work if we didn't have an mpi compiler, but then again, mfem would not have been compiled with mpi if there was no mpi compiler.

**Comment by mclarsen** [comment]
With zero copy = true with BlueprintMeshToMesh in mfem, how are we supposed to know if the constraints were not met and the data should be deleted or not?

**Comment by mclarsen** [comment]
Here is the situation: Laghos (fmem) ->blueprint (Ascent)->mfem (data adapter to linearize)->blueprint->vtkm

As I mentioned before, this brings up the question of memory management. In the beginning, all we had was simulation data and vtkh filters and that made memory ownership semantics simple. We assumed that the simulation memory was zero copied whether is was or not. When the data got to vtkh, it was transformed (e.g., isosurface) which resulted in new data. Memory never had to exist past the execution of the next filter, and this is exactly what flow expected.

With the addition of mfem mesh low order conversion, this adds some complications where memory needs to exist past the next filter.  We could just copy everything past the initial sim data, but this is suboptimal. We could play games with the registry, but this seems like it would get complicated and hard to manage. I think the ideal solution would be to memory transfer semantics.

With memory transfer (i.e., i am giving you memory that you now own), there is a single filter handoff and no responsibility beyond that. I am pretty sure this is supported under the covers in vtkm, but this is not supported by conduit.

**Comment by mclarsen** [comment]
I cleaned up the vtkh data adapter code a bit and added support for:

-  zero copy or not
- detection and zero copy of interleaved coordinate systems (Laghos). I still need to identify a stride of three when it is a 2d coordinate system. That is, blueprint only reports x and y, but there secretly is a z component of 0s in the underlying memory.
- Registry reference count bump when EnsureLowOrder converts a high order mesh to low.

**Comment by mclarsen** [comment]
One other note. Instead of always checking all over to is if a blueprint data set is multi_dom, I am just converting it on publish. This way its always multi dom.

**Comment by mclarsen** [comment]
@cyrush Any idea why the static build would be failing on the python extract?

**Comment by mclarsen** [comment]
@cyrush Can you review when you have a chance?

**Review by cyrush — COMMENTED** [review]
@mclarsen looks awesome, thanks for working all of this out!

**Pull request merged**
