### PR TITLE
adds save_info action

### PR DESCRIPTION
**Pull request by cyrush**
and also adds published mesh details to Ascent::info() tree

### CODE REVIEW

**Comment by cyrush** [comment]
need to dig more b/c hola mpi consistently crashes in CI post these changes

[hola_mpi_crash_log.txt](https://github.com/Alpine-DAV/ascent/files/7793650/hola_mpi_crash_log.txt)

**Comment by nicolemarsaglia** [comment]
This should be fixed with [Conduit PR 985](https://github.com/LLNL/conduit/pull/985)

**Comment by cyrush** [comment]
We should be good to merge this post #995

**Comment by cyrush** [comment]
@nicolemarsaglia thanks for the conduit fix, we are now good here. Merging.

**Pull request merged**
