### PR TITLE
Bflow dray integ

### PR DESCRIPTION
**Pull request by sshudler**
Recent changes in BabelFlow compositing extract (rebased the branch for easier merge and cleaner history):
- Support for composable graphs
- Unit-test to test the compositing extract
- Integration with dray renderer

@mclarsen I merged the 'dray_render_filter' branch into this branch, so this PR will integrate the dray related changes in 'develop'

### CODE REVIEW

**Comment by cyrush** [comment]
@sshudler I can update our CI containers to include babelflow as part of the non-cuda build. 
I am going to do a test merge of the latest CI scripts from into this branch, if that looks good, I will merge in them in to this branch and start the process to update the container.

**Comment by cyrush** [comment]
ok, I updated TPL container to use an uberenv build with `+babelflow`, lets double check everything gets exercised as expected.

**Comment by cyrush** [comment]
@sshudler,
Looks like it failed, -- I built with uberenv setup on this branch, do we need to update the babelflow branches, etc?

**Comment by sshudler** [comment]
@cyrush Yes, it looks like the package script 'scripts/uberenv/packages/babelflow/package.py' points to an older commit, I updated it now

**Comment by cyrush** [comment]
@sshudler thanks, I'll pull and rebuild the container!

**Comment by sshudler** [comment]
@cyrush The BabelFlow PMT unit test fails... It looks like the rendered image is different from the baseline. I used Ascent's volume rendering to render the segmentation field we extract using PMT. But the question is there any reason for the rendering (in the container) to be different compared to how it was volume rendered on my Mac?

**Comment by cyrush** [comment]
There can be differences between machines, if so we can up the tolerance to get a pass. 

That said, it looks like maybe the file itself is missing?

```
020-09-14T23:14:37.0005664Z 69: test_file: 
2020-09-14T23:14:37.0010908Z 69:   path: "/__w/1/s/build/tests/_output/tout_babelflow_pmt_mpi0.png"
2020-09-14T23:14:37.0016144Z 69:   exists: "false"
2020-09-14T23:14:37.0019292Z 69: baseline_file: 
2020-09-14T23:14:37.0024242Z 69:   path: "/__w/1/s/src/tests/baseline_images/tout_babelflow_pmt_mpi0.png"
2020-09-14T23:14:37.0032410Z 69:   exists: "true"
2020-09-14T23:14:37.0032822Z 69: 
```

You should be able to download all the results to explore more. 

https://dev.azure.com/alpine-dav/Ascent/_build/results?buildId=864&view=artifacts&type=publishedArtifacts

For those tests that did log, you can see them by looking at the following html file in the downloaded artifacts:
/build/tests/_output/tout_img_report.html

It looks like some worked as expected, maybe a typo or something simple undermining the others?

**Comment by cyrush** [comment]
here is an example of one that seems to have worked:

Screen Shot 2020-09-14 at 4 34 14 PM

**Comment by sshudler** [comment]
@cyrush I downloaded the results and checked the report and it seems that the other Babelflow test passed ok:

Screen Shot 2020-09-15 at 6 12 30 PM

I also double checked that the baseline image exists in the branch. But it's still strange that that the log shows the output file was not created, as if the test failed somewhere in the middle...

**Comment by cyrush** [comment]
I tested in the container -- first time it fails:

```
root@055ff3c70897:/ascent/build-debug# rm -rf tests/_output/*
root@055ff3c70897:/ascent/build-debug# ctest -VV -R t_ascent_babelflow_pmt_mpi
Total Test time (real) =   5.17 sec

The following tests FAILED:
	 69 - t_ascent_babelflow_pmt_mpi (Failed)
```

But the next time it runs it passes:

```
root@055ff3c70897:/ascent/build-debug# ctest -VV -R t_ascent_babelflow_pmt_mpi
The following tests passed:
	t_ascent_babelflow_pmt_mpi

100% tests passed, 0 tests failed out of 1
```

A few ideas:
* It could be relying on a image that is created at the wrong time
* It could be an MPI vs file system issue, you need a barrier somewhere before the test

If you have docker  on your machine, you can explore yourself using:

`docker run -it alpinedav/ascent-ci:ubuntu-18-devel-tpls_2020-09-14-sha602e66`

Check out ascent yourself, and use the tpls in `/uberenv_libs/`

Here is how I added cmake to my path in the container:

`export PATH=$PATH:/uberenv_libs/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.5.0/cmake-3.14.5-c2kpth3e6gstu33yyq5j5oi56y6utw6o/bin/`

**Comment by sshudler** [comment]
@cyrush You're right about the barrier, all the other unit tests using MPI have one before comparing the results. I don't have Docker on my mac (requires admin access to install it), so hopefully the barrier thing will fix the issue.

**Comment by cyrush** [comment]
Great -- looks like that sovled the issue!

**Review by cyrush — APPROVED** [review]
looks good to me, @mclarsen do you want to take a look?

**Review by mclarsen — APPROVED** [review]

**Pull request merged**
