### PR TITLE
add support for specifying actions with yaml

### PR DESCRIPTION
**Pull request by cyrush**

### CODE REVIEW

**Comment by cyrush** [comment]
not perfect, but my first pass that includes a test for passing actions via a yaml file

**Comment by mclarsen** [comment]
Looking good.

**Comment by mclarsen** [comment]
What does ` "<<UNSET>>"` mean?

**Comment by cyrush** [comment]
i set it to a goofy  `<<UNSET>>` default value to indicate that we should check for either `ascent_actions.json` OR `ascent_actions.yaml`. There are probably better ways to plum this

**Pull request merged**
