### PR TITLE
Add the htg extract filter.

### PR DESCRIPTION
**Pull request by brugger1**
Added the htg extract filter. The filter outputs a HyperTreeGrid (HTG) as an ASCII VTK htg file. The file can viewed with ParaView 5.9.0-RC3 or later.

I also added a test for it which creates a basic uniform grid and saves it using the htg extract filter.

### CODE REVIEW

**Comment by nicolemarsaglia** [comment]
Overall, looks good. Is there a use case for htg + mpi? If so, does it need logic for parallel coordination?

**Comment by brugger1** [comment]
There's the potential to do this in parallel if the meshes on all the ranks fit together properly. That would be a bunch of additional development, so I'll wait with that for another day.

**Comment by nicolemarsaglia** [comment]
Sounds good. In that case, I'm going to add an #if ASCENT_MPI_ENABLED that will throw an ASCENT_ERROR in execute(). And then I think we are good to go.

**Review by nicolemarsaglia — APPROVED** [review]
Looks good.

**Comment by brugger1** [comment]
Thanks for the improvement and merging!!

**Pull request merged**
