### PR TITLE
Add ParaView vis. using Python Extracts

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@cyrush @mclarsen @utkarshayachit Please review.

**Comment by cyrush** [comment]
@danlipsa, i think this looks good!

I have one suggested change which would be helpful for future understanding.  I see you use json to name many variables in the conduit to vtk binding code.  The stuff passed in isn't really json, it's a Conduit Node -- that may confuse folks into thinking it's consuming json strings or using some python json api. 

Would it be hard to change the names to refer to conduit instead of json?

**Comment by danlipsa** [comment]
@cyrush Sounds good. Indeed, that variable name can be confusing. I'll make the change.

**Comment by danlipsa** [comment]
@cyrush I made the change suggested.

**Comment by cyrush** [comment]
Looks good thanks!

**Pull request merged**
