### PR TITLE
Add ghosts

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@cyrush @mclarsen Please review. This is a small change to mark the ghost cells coming from Ascent in VTK and change the vis for cloverleaf to remove the ghost cells. Thanks!

**Review by cyrush — APPROVED** [review]
Looks good to me :-)

**Comment by danlipsa** [comment]
@cyrush I don't have write access to the repo, can you merge please? Thanks!

**Comment by cyrush** [comment]
@danlipsa done, thanks!

**Pull request merged**
